# Generated by Django 5.1.1 on 2024-10-01 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_usuario_rol_usuario_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefono',
        ),
    ]
