# Generated by Django 5.1.1 on 2024-10-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_remove_producto_imagen_producto_destacado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
