# Generated by Django 5.1.1 on 2024-10-17 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='Destacado',
            new_name='destacado',
        ),
    ]
