# Generated by Django 5.1.1 on 2024-11-03 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import datetime 

class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_rename_destacado_producto_destacado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='fecha_orden',
            field=models.DateField(default=datetime.date.today),  # Set today's date as the default
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orden',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
